<?php
add_action('init', function() {
  pll_register_string('Тема', 'Новости');
  pll_register_string('Тема', 'Общее');
  pll_register_string('Тема', 'Территория');
  pll_register_string('Тема', 'Население');
  pll_register_string('Тема', 'Экономика');
  pll_register_string('Тема', 'Новости');
  pll_register_string('Тема', 'Туризм');
  pll_register_string('Тема', 'км');
  pll_register_string('Тема', 'Связаться');
  pll_register_string('Тема', 'Курганская область');
  pll_register_string('Тема', 'Фотогалерея');
  pll_register_string('Тема', 'Показать на карте');
  pll_register_string('Тема', 'Оборот, млн. р');
  pll_register_string('Тема', 'Показать ещё');
  pll_register_string('Тема', 'Меры поддержки');
  pll_register_string('Тема', 'Территории<br> опережающего развития');
  pll_register_string('Тема', 'ТОР');
  pll_register_string('Тема', 'Индустриальные<br> парки');
  pll_register_string('Тема', 'Особая<br> экономическая зона');
  pll_register_string('Тема', 'Инвестиционная<br> карта');
  pll_register_string('Тема', 'Инвестиционные<br> площадки');
  pll_register_string('Тема', 'Консультация<br> специалиста');
  pll_register_string('Тема', 'Предлагаемые');
  pll_register_string('Тема', 'Реализуемые');
  pll_register_string('Тема', 'Истории успеха');
  pll_register_string('Тема', 'Список отраслей<br> или видов деятельности');
  pll_register_string('Тема', 'Размер инвестиций');
  pll_register_string('Тема', 'Объём<br> инвестиций');
  pll_register_string('Тема', 'Политика конфиденциальности');
  pll_register_string('Тема', 'Разработка сайта');
  pll_register_string('Тема', 'млн.');
  pll_register_string('Тема', 'лет');
  pll_register_string('Тема', 'год');
  pll_register_string('Тема', 'года');
  pll_register_string('Тема', 'Срок<br> окупаемости');
  pll_register_string('Тема', 'Назад');
  pll_register_string('Тема', 'Скачать презентацию');
  pll_register_string('Тема', 'Контакты');
  pll_register_string('Тема', 'Координатор проекта');
  pll_register_string('Тема', 'Координаты проекта');
  pll_register_string('Тема', 'Об агентстве');
  pll_register_string('Тема', 'Документы');
  pll_register_string('Тема', 'Структура');
  pll_register_string('Тема', 'Прямая связь');
  pll_register_string('Тема', 'Направить обращение');
  pll_register_string('Тема', 'Видеообращение губернатора');
  pll_register_string('Тема', 'Задайте вопрос');
  pll_register_string('Тема', 'Все меры поддержки');
  pll_register_string('Тема', 'Подробнее');
  pll_register_string('Тема', 'Результаты поиска:');
  pll_register_string('Тема', 'К сожалению ничего не найдено:');
});